Final deploy

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -325,40 +325,39 @@ jobs:
       - destroy-environment
       - revert-migrations              
 
-  # smoke-test:
-  #   docker:
-  #     - image: circleci/node:13.8.0
-  #   steps:
-  #     - checkout
-  #     - run:
-  #         name: Install dependencies
-  #         command: |
-  #           sudo apt install curl
-  #     - attach_workspace:
-  #         at: ~/
-  #     - run:
-  #         name: Backend smoke test.
-  #         command: |
-  #           export BACKEND_IP=$(tail -1 ~/project/.circleci/ansible/inventory.txt)
-  #           export API_URL="http://${BACKEND_IP}:3030/api/status"
-  #           echo "${API_URL}"
-  #           sleep 30
-  #           curl ${API_URL}
-  #     - run:
-  #         name: Frontend smoke test.
-  #         command: |
-  #           export FRONTEND_IP="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"
-  #           if curl -s ${FRONTEND_IP} | grep "Welcome"
-  #           then
-  #             echo "pass"
-  #             exit 0
-  #           else
-  #             echo "fail"
-  #             exit 1
-  #           fi
-  #     # Here's where you will add some code to rollback on failure  
-  #     - revert-migrations
-  #     - destroy-environment
+  smoke-test:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            sudo apt install curl
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Backend smoke test.
+          command: |
+            export BACKEND_IP=$(tail -1 ~/project/.circleci/ansible/inventory.txt)
+            export API_URL="http://${BACKEND_IP}:3030/api/status"
+            echo "${API_URL}"
+            sleep 30
+            curl ${API_URL}
+      - run:
+          name: Frontend smoke test.
+          command: |
+            export FRONTEND_IP="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"
+            if curl -s ${FRONTEND_IP} | grep "Welcome"
+            then
+              echo "pass"
+              exit 0
+            else
+              echo "fail"
+              exit 1
+            fi
+      - revert-migrations
+      - destroy-environment
 
   cloudfront-update:
     docker:
@@ -436,5 +435,7 @@ workflows:
           requires: [run-migrations]
       - cloudfront-update:
            requires: [deploy-backend]
+      - smoke-test:
+          requires: [cloudfront-update]
       - cleanup:
           requires: [cloudfront-update]
